# Generated by Django 4.1 on 2022-09-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_alter_author_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.FileField(default=None, upload_to='ebook/%Y/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.ImageField(upload_to='author_pics/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(upload_to='ebook/%Y/'),
        ),
    ]
